$imagePath = "../images/snippetica-logo-large.png"

Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix/Snippetica.Cpp/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix/Snippetica.CSharp/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix/Snippetica.Html/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix/Snippetica.Json/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix/Snippetica.Markdown/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix/Snippetica.VisualBasic/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix/Snippetica.Xml/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix.Dev/Snippetica.Cpp.Dev/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix.Dev/Snippetica.CSharp.Dev/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix.Dev/Snippetica.Html.Dev/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix.Dev/Snippetica.Markdown.Dev/package/images/icon.png"
Copy-Item $imagePath "../src/Snippetica.VisualStudioCode.Vsix.Dev/Snippetica.VisualBasic.Dev/package/images/icon.png"
