using System.Diagnostics;
using System.IO;

namespace Pihrtsoft.Snippets.CodeGeneration.Commands
{
    public class XamlPropertyCommand : BaseCommand
    {
        public override CommandKind Kind
        {
            get { return CommandKind.XamlProperty; }
        }

        protected override void Execute(ExecutionContext context, Snippet snippet)
        {
            snippet.SuffixTitle(" property");
            snippet.SuffixShortcut("py");
            snippet.SuffixDescription(" property");
            snippet.RemoveTag(KnownTags.GenerateXamlProperty);
            snippet.RemoveTag(KnownTags.NonUniqueShortcut);
            snippet.AddTag(KnownTags.AutoGenerated);

            snippet.Literals.Clear();
            snippet.AddLiteral("property", "Property name", ".");

            string name = Path.GetFileNameWithoutExtension(snippet.FilePath);

            snippet.CodeText = $"<{name}$property$>$end$</{name}$property$>";

            snippet.SuffixFileName("Property");
        }
    }
}
